// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CampusLocation struct {
	Location Location `json:"location"`
}

type City struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
}

type Country struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
}

type CreateStudentInput struct {
	UUID             string `json:"uuid"`
	FirstName        string `json:"firstName"`
	LastName         string `json:"lastName"`
	Email            string `json:"email"`
	LinkedInPhotoURL string `json:"linkedInPhotoURL"`
}

type Filters struct {
	Locations    []Location `json:"locations"`
	PaymentTypes []string   `json:"paymentTypes"`
	MinLengths   []int      `json:"minLengths"`
	MaxPrices    []int      `json:"maxPrices"`
}

type Location struct {
	UUID    string  `json:"uuid"`
	City    City    `json:"city"`
	Country Country `json:"country"`
}

type NewReviewParams struct {
	StudentUUID            string  `json:"studentUUID"`
	Title                  string  `json:"title"`
	StudentExperience      string  `json:"studentExperience"`
	StudentAdvice          *string `json:"studentAdvice"`
	OverallScore           int     `json:"overallScore"`
	TeachingScore          int     `json:"teachingScore"`
	CourseworkScore        int     `json:"courseworkScore"`
	AtmosphereScore        int     `json:"atmosphereScore"`
	CareerPreparationScore int     `json:"careerPreparationScore"`
	SchoolUUID             string  `json:"schoolUUID"`
	SchoolLocationUUID     string  `json:"schoolLocationUUID"`
	DidGraduate            bool    `json:"didGraduate"`
	SchoolGraduationMonth  *int    `json:"schoolGraduationMonth"`
	SchoolGraduationYear   *int    `json:"schoolGraduationYear"`
	HasJob                 bool    `json:"hasJob"`
	SalaryBefore           *int    `json:"salaryBefore"`
	SalaryAfter            *int    `json:"salaryAfter"`
	JobLocationUUID        *string `json:"jobLocationUUID"`
	JobLocationOtherName   *string `json:"jobLocationOtherName"`
	JobStartMonth          *int    `json:"jobStartMonth"`
	JobStartYear           *int    `json:"jobStartYear"`
}

type Review struct {
	UUID                      string    `json:"uuid"`
	Title                     string    `json:"title"`
	StudentExperience         string    `json:"studentExperience"`
	StudentAdvice             *string   `json:"studentAdvice"`
	TeachingScore             int       `json:"teachingScore"`
	CourseworkScore           int       `json:"courseworkScore"`
	AtmosphereScore           int       `json:"atmosphereScore"`
	CareerPreparationScore    int       `json:"careerPreparationScore"`
	OverallScore              int       `json:"overallScore"`
	HelpfulUpvotes            int       `json:"helpfulUpvotes"`
	HelpfulDownvotes          int       `json:"helpfulDownvotes"`
	DidGraduate               bool      `json:"didGraduate"`
	HasJob                    bool      `json:"hasJob"`
	SalaryBefore              *int      `json:"salaryBefore"`
	SalaryAfter               *int      `json:"salaryAfter"`
	School                    School    `json:"school"`
	SchoolLocation            Location  `json:"schoolLocation"`
	SchoolGraduationTimestamp *int      `json:"schoolGraduationTimestamp"`
	JobLocation               *Location `json:"jobLocation"`
	JobStartTimestamp         *int      `json:"jobStartTimestamp"`
	CreatedTimestamp          int       `json:"createdTimestamp"`
}

type School struct {
	UUID                string               `json:"uuid"`
	Name                string               `json:"name"`
	LengthInWeeks       *int                 `json:"lengthInWeeks"`
	StudentTeacherRatio *int                 `json:"studentTeacherRatio"`
	IsOnline            *bool                `json:"isOnline"`
	BasePrice           *int                 `json:"basePrice"`
	PaymentType         *string              `json:"paymentType"`
	PhotoURI            *string              `json:"photoURI"`
	CampusLocations     []CampusLocation     `json:"campusLocations"`
	ReviewSummary       *SchoolReviewSummary `json:"reviewSummary"`
}

type SchoolQueryResult struct {
	TotalNumResults int      `json:"totalNumResults"`
	PageNumber      int      `json:"pageNumber"`
	SchoolResults   []School `json:"schoolResults"`
}

type SchoolReviewSummary struct {
	TotalNumReviews           int     `json:"totalNumReviews"`
	OverallScore              float64 `json:"overallScore"`
	TeachingScore             float64 `json:"teachingScore"`
	CourseworkScore           float64 `json:"courseworkScore"`
	AtmosphereScore           float64 `json:"atmosphereScore"`
	CareerPreparationScore    float64 `json:"careerPreparationScore"`
	AverageSalaryBefore       *int    `json:"averageSalaryBefore"`
	AverageSalaryAfter        *int    `json:"averageSalaryAfter"`
	AverageMonthsToAcquireJob *int    `json:"averageMonthsToAcquireJob"`
}

type SchoolSearchParams struct {
	PageNumber   int     `json:"pageNumber"`
	SearchText   *string `json:"searchText"`
	LocationUUID *string `json:"locationUUID"`
	PaymentType  *string `json:"paymentType"`
	MaxPrice     *int    `json:"maxPrice"`
	MinLength    *int    `json:"minLength"`
}

type Student struct {
	UUID             string  `json:"uuid"`
	FirstName        string  `json:"firstName"`
	LastName         string  `json:"lastName"`
	PhotoURI         *string `json:"photoURI"`
	LinkedInPhotoURL *string `json:"linkedInPhotoURL"`
	School           *School `json:"school"`
}

type UpdateStudentInput struct {
	UUID        string  `json:"uuid"`
	FirstName   *string `json:"firstName"`
	LastName    *string `json:"lastName"`
	Email       *string `json:"email"`
	LinkedInURL *string `json:"linkedInURL"`
	SchoolUUID  *string `json:"schoolUUID"`
}
