// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Location struct {
	UUID    string  `json:"uuid"`
	City    *string `json:"city"`
	Country string  `json:"country"`
}

type School struct {
	UUID              string     `json:"uuid"`
	Name              string     `json:"name"`
	AvgGraduateSalary *float64   `json:"avgGraduateSalary"`
	AcceptanceRate    *float64   `json:"acceptanceRate"`
	JobPlacementRate  *float64   `json:"jobPlacementRate"`
	LengthInWeeks     *int       `json:"lengthInWeeks"`
	IsOnline          *bool      `json:"isOnline"`
	BasePrice         *int       `json:"basePrice"`
	PaymentType       *string    `json:"paymentType"`
	PhotoURI          *string    `json:"photoURI"`
	Locations         []Location `json:"locations"`
	Tracks            []Track    `json:"tracks"`
}

type SchoolSearchParams struct {
	Country                         *string `json:"country"`
	TrackUUID                       *string `json:"trackUUID"`
	PaymentType                     *string `json:"paymentType"`
	SortByPriceLowToHigh            *bool   `json:"sortByPriceLowToHigh"`
	SortByPriceHighToLow            *bool   `json:"sortByPriceHighToLow"`
	SortByGraduateSalaryHighToLow   *bool   `json:"sortByGraduateSalaryHighToLow"`
	SortByJobPlacementRateHighToLow *bool   `json:"sortByJobPlacementRateHighToLow"`
	MinLength                       *int    `json:"minLength"`
	IsOnline                        *bool   `json:"isOnline"`
}

type Track struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
}
