// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Occupation struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type School struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
